src/components/app/admin.component.tsx
src/components/app/modules/donorselector.actions.ts
src/components/app/modules/donorselector.component.style.tsx
src/components/app/modules/donorselector.component.tsx
src/components/app/modules/donorselector.reducer.ts
src/components/app/pages/home/home.component.tsx
src/components/app/pages/register/register.component.tsx
src/models/dbtypes.ts
src/models/state.ts
src/store.ts

Adds first iteration of donor selector component

Donor selection 

---

src/components/modules/kid/KIDComponent.tsx
src/components/modules/single-donation/input/DonationInput.tsx
src/models/types.ts

#146 Changes KID type to string

---

src/store/avtalegiro/avtalegiro.reducer.ts

Sets share as decimal

---

src/components/modules/donations/list/DonationsList.tsx
src/components/pages/distributions/Distribution.tsx
src/components/pages/distributions/DistributionKeyInfo.tsx
src/store/avtalegiro/avtalegiro.reducer.ts
src/store/distributions/distributions.reducer.ts
src/store/distributions/distributions.saga.ts

Distribution page

---

package-lock.json
package.json
src/components/modules/report-upload/ReportUpload.tsx
src/components/style/elements/loading-spinner.tsx
src/models/state.ts
src/store/process/process.reducer.ts

Adds a spinner next to the process button while processing a report.

Add visual cue for processing reports

---

src/components/modules/distribution/list/DistributionsList.tsx
src/components/modules/donors/selection/DonorSelection.tsx
src/components/pages/distributions/Distributions.tsx
src/store/avtalegiro/avtalegiro.reducer.ts
src/store/distributions/distributions.reducer.ts
src/store/donations/donations.reducer.ts
src/store/vipps/vipps.reducer.ts

Prettier changes a lot. Should I remove or is it fine?

220 load 25 rows at default for all list views

---

src/components/modules/distribution/list/DistributionsList.tsx
src/components/pages/donors/Donor.tsx
src/store/donors/donor-page.saga.ts

Requires merging this first: https://github.com/stiftelsen-effekt/effekt-backend/pull/384

Fixes DistributionList for individual donor view

---

src/components/modules/avtalegiro/agreementlist/AvtaleGiroFilter.tsx
src/components/modules/donations/list/filters/DonationsFilter.tsx

Fixes Nan bug in filters

---

src/components/modules/distribution/list/DistributionsList.tsx
src/components/modules/donations/list/DonationsList.tsx
src/components/pages/distributions/Distribution.tsx
src/models/state.ts
src/store/distributions/distributions.reducer.ts
src/store/distributions/distributions.saga.ts

fixed distribution page loading and ID

---

package-lock.json
src/components/modules/facebook/FBCampaignSharesRegistration.style.tsx
src/components/modules/facebook/FBCampaignSharesRegistration.tsx
src/components/modules/kid/KIDComponent.style.tsx
src/components/modules/kid/KIDComponent.tsx
src/components/modules/report-upload/ReportUpload.tsx
src/components/pages/process/ProcessDonations.tsx
src/components/pages/register/Register.tsx
src/config/config.ts
src/models/state.ts
src/models/types.ts
src/root.saga.ts
src/store/facebook/facebook.actions.ts
src/store/facebook/facebook.saga.ts
src/store/process/process.reducer.ts
src/store/report/report-upload.actions.ts
src/store/report/report-upload.saga.ts

Designed and implemented FB report upload in the admin panel. After uploading, one is first asked to input the shares for new FB campaigns. 
Then, one is redirected to another page in case of invalid transactions.
The donation sum we get from FB is in EUR. Norges Bank exchange rates are used to get NOK. If the payment was in NOK, the NOK sum is also rounded using the two first digits. E.g., 896 -> 900, 4720 -> 4700. If the difference between the original sum and the sum rounded using only the first digit is more than 3 percent, the sum is only rounded with the first digit. e.g., 97  -> 100, 96  -> 96, 99  -> 100, 970  -> 1000, 485  -> 500

Facebook import

---

src/components/pages/avtalegiro/AvtaleGiroAgreement/AvtaleGiroAgreement.tsx

The default status when editing AG agreements is now the actual current status

edit AG agreement correct default status

---

src/components/modules/donations/list/filters/DonationsFilter.tsx
src/models/types.ts
src/store/donations/donation-filters.actions.ts
src/store/donations/donations.reducer.ts

Also auto select every payment method when no payment method is selected.

donations filter payment methods auto selected by default

---

src/components/modules/donations/list/DonationsList.style.tsx
src/components/modules/donations/list/DonationsList.tsx
src/components/pages/distributions/Distribution.tsx
src/components/pages/donations/Donation.tsx
src/store/donations/donation.actions.ts
src/store/donations/donations-list.actions.ts
src/store/donations/donations-list.saga.ts

Fixed and moved delete donation button to donation page

---

src/components/pages/donors/Donor.style.tsx
src/components/pages/donors/Donor.tsx
src/components/pages/donors/donor/TotalDonationAmount.style.tsx
src/components/pages/donors/donor/TotalDonationAmount.tsx

a table of total donations and total donations minus operations
donations, in the same style as the key info table.
resolves #184
Could not get it to always show 2 decimals with thousandize. Is there a way? Ended up doing toFixed(2), wrapping that in Number() and doing thousandize() on that, but as soon as it's just an number it forgets that I wanted two decimals. Thought variable # of decimals was better than rounding to nearest kr.

adminpanel/donors: add total donation amount

---

src/components/pages/donors/donor/KeyInfo.tsx

Just stumbled across something that looked like a bug...

DonorKeyInfo: Actually show newsletter/trash data

---

src/App.tsx

This prevents excessive entries of OTP tokens while developing

App: Use local storage for auth0 tokens in dev

---

src/util/api.ts

Appears to just have been a minor ... forgotten detail in the original implementation?

API: Support PUT

---

src/components/modules/avtalegiro/agreementlist/AvtaleGiroList.tsx
src/components/modules/distribution/list/DistributionsList.tsx
src/components/modules/donations/list/DonationsList.tsx
src/components/modules/donors/selection/DonorSelection.tsx
src/components/modules/logs/list/LogsList.tsx
src/components/modules/vipps/agreementlist/VippsAgreementList.tsx
src/components/modules/vipps/chargelist/VippsAgreementChargeList.tsx
src/components/style/elements/react-table/base.css
src/components/style/elements/react-table/table.css

And do line break instead of elision when the content in a cell is too long
https://github.com/stiftelsen-effekt/effekt-admin/issues/152

Set default column widths

---

src/config/config.ts

This can help prevent users from accidentally changing things in production envs

Config: sensible default API_URL on DEV envs

---

src/components/modules/distribution/list/DistributionsList.tsx

This closes issue #251
Easiest. Bugfix. Ever.

Donor: Fix double click feature on distribution.

---

src/components/modules/donors/referral_answers/ReferralAnswerList.tsx
src/components/pages/donors/Donor.tsx
src/models/state.ts
src/models/types.ts
src/root.saga.ts
src/store/donors/donor-page.actions.ts
src/store/donors/donor-page.reducer.ts
src/store/donors/donor-page.saga.ts

This closes issue #206
@JorgenLjones @fellmirr

Donor: Add referral answer tab.

---

src/components/modules/donations/list/filters/DonationsFilter.tsx
src/models/types.ts
src/store/donations/donation-filters.actions.ts
src/store/donations/donations.reducer.ts

Donation: Allow filter by ID.

---

src/components/pages/avtalegiro/AvtaleGiroAgreement/AvtaleGiroAgreement.tsx

I dont't understand the semantics of "manual" ... but clearly, setting it to false yields correct pagiantion.

AvtaleGiroAgreement: Make pagination work

---

src/components/pages/avtalegiro/AvtaleGiroAgreement/AvtaleGiroAgreement.tsx

Remote Donor and KID fields from AG page

---

src/components/modules/donors/selection/DonorSelection.tsx
src/models/types.ts

This fixes issue #463
Note that this requires that stiftelsen-effekt/effekt-backend#463 be merged

Donors: Include total donations in list.

---

package-lock.json
package.json
src/components/modules/avtalegiro/agreementlist/AvtaleGiroFilter.tsx
src/components/style/elements/effekt-range/effekt-range.component.style.tsx
src/components/style/elements/effekt-range/effekt-range.component.tsx
src/models/types.ts
src/store/avtalegiro/avtalegiro.actions.ts
src/store/avtalegiro/avtalegiro.reducer.ts

This is part of the work on issue #128
Requires changes from stiftelsen-effekt/effekt-backend#465

AvtaleGiro: Add charge day filter.

---

src/components/modules/avtalegiro/agreementlist/AvtaleGiroFilter.tsx
src/models/types.ts
src/store/avtalegiro/avtalegiro.actions.ts
src/store/avtalegiro/avtalegiro.reducer.ts

This is part of the work on issue #128

AvtaleGiro: Add created date filter (draft date)

---

src/components/modules/avtalegiro/agreementlist/AvtaleGiroFilter.tsx
src/components/modules/donations/list/filters/DonationsFilter.tsx
src/models/state.ts
src/root.saga.ts
src/store/organizations/organizations.action.ts
src/store/organizations/organizations.reducer.ts
src/store/organizations/organizations.saga.ts

- Add action, saga, reducer and dispatch to get all organizations
Note: **Depends on backend change https://github.com/stiftelsen-effekt/effekt-backend/pull/468**

Fix missing organizations in filter on donations page

---

src/components/modules/donors/selection/DonorSelection.tsx
src/components/style/elements/filters.component.style.tsx
src/store/donors/donor-selection.actions.ts
src/store/donors/donor-selection.saga.ts

Note that this requires corresponding backend change to not break.
This closes issue #265

Donors: Add filters

---

src/components/modules/avtalegiro/agreementlist/AvtaleGiroFilter.tsx
src/components/modules/vipps/agreementlist/VippsAgreementFilter.tsx
src/models/types.ts
src/store/vipps/vipps.actions.tsx
src/store/vipps/vipps.reducer.ts

This closes issue #127
NOTE: Requires changes from stiftelsen-effekt/effekt-backend#471

Vipps agreements: Add charge day / draft date filters

---

src/components/modules/avtalegiro/agreementlist/AvtaleGiroFilter.tsx
src/models/types.ts

Fixes the issue where AvtaleGiro statuses were not correctly highlighted
#241 
---
Tests  

Updates types for avtalegiro status selctor

---

src/components/pages/donors/Donor.tsx

Changes name "Vipps" to "Vipps recurring" in donors
#252
---
Tests  

Changes name "Vipps" to "Vipps recurring" in donors"

---

src/components/Navigation.style.tsx

added scroll bar to Navigation
#336 
---
Tests  
⏲️ Time spent on CR: 5 min
⏲️ Time spent on QA: 5 min

added scroll bar to Navigation

---

src/components/pages/donors/donor/AggregateChart.tsx

fixed donor donation agregates
#337
---
Tests  

fixed donor donation agregates

---

src/components/modules/taxunits/create/CreateTaxUnit.tsx
src/components/modules/vipps/agreementlist/VippsAgreementList.tsx
src/components/pages/donors/Donor.tsx
src/components/style/elements/create.style.tsx
src/models/state.ts
src/root.saga.ts
src/store.ts
src/store/taxunits.ts/taxunits.actions.ts
src/store/taxunits.ts/taxunits.reducer.ts
src/store/taxunits.ts/taxunits.saga.ts

Added button for creating new tax unit
#343 
---
Tests  

Added button for creating new tax unit

---

.env.example
README.md
clouddeploy.dev.yml
clouddeploy.yml
src/App.tsx
src/config/config.ts

https://github.com/stiftelsen-effekt/admin/issues/20
---
Tests  

Allow configurable auth0

---

src/models/state.ts
tsconfig.json

Aligns with rules for building in CI where unused vars are treated as errors
---
Tests  

Detect unused vars when typechecking

---

src/components/Navigation.style.tsx

Fixes a overflow issue where scrollbars would appear on large screens
#83 fixes issue related to this fix
---
Tested on devices
Tests

Fixes visual scroll bug in menu

---

src/components/modules/report-upload/ReportUpload.tsx
src/store/process/process.reducer.ts
src/store/report/report-upload.actions.ts
src/store/report/report-upload.saga.ts

- closes #373 
---
Tested on devices
Tests

Finishing touches
